name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # This triggers the workflow on version tags, like v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        architecture: [x86_64, arm64]
        exclude:
          - os: windows-latest
            architecture: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build application with PyInstaller
        run: |
          pyinstaller easydiver.spec --noconfirm

      - name: Zip the output
        run: |
          zip -r EasyDiver-${{ matrix.os }}-${{ matrix.architecture }}.zip dist/EasyDiver

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: easydiver-${{ matrix.os }}-${{ matrix.architecture }}
          path: EasyDiver-${{ matrix.os }}-${{ matrix.architecture }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: easydiver-*
          path: ./dist

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release notes for ${{ github.ref }}.
          draft: false
          prerelease: false
          files: ./dist/*.zip