name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # This triggers the workflow on version tags, like v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        architecture: [x86_64, arm64]
        exclude:
          - os: windows-latest
            architecture: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build application with PyInstaller
        run: |
          pyinstaller easydiver.spec --noconfirm

      - name: Zip the output (Linux and macOS)
        if: runner.os != 'Windows'
        run: |
          zip -r EasyDiver-${{ matrix.os }}-${{ matrix.architecture }}.zip dist/EasyDiver

      - name: Zip the output (Windows)
        if: runner.os == 'Windows'
        run: |
          Compress-Archive -Path dist/EasyDiver -DestinationPath EasyDiver-${{ matrix.os }}-${{ matrix.architecture }}.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: easydiver-${{ matrix.os }}-${{ matrix.architecture }}
          path: EasyDiver-${{ matrix.os }}-${{ matrix.architecture }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts (Ubuntu x86_64)
        uses: actions/download-artifact@v2
        with:
          name: easydiver-ubuntu-latest-x86_64
          path: ./dist

      - name: Download build artifacts (Ubuntu arm64)
        uses: actions/download-artifact@v2
        with:
          name: easydiver-ubuntu-latest-arm64
          path: ./dist

      - name: Download build artifacts (Windows x86_64)
        uses: actions/download-artifact@v2
        with:
          name: easydiver-windows-latest-x86_64
          path: ./dist

      - name: Download build artifacts (macOS x86_64)
        uses: actions/download-artifact@v2
        with:
          name: easydiver-macos-latest-x86_64
          path: ./dist

      - name: Download build artifacts (macOS arm64)
        uses: actions/download-artifact@v2
        with:
          name: easydiver-macos-latest-arm64
          path: ./dist

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}  # Use the PAT secret here
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Release notes for ${{ github.ref }}.
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}  # Use the PAT secret here
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/*.zip
          asset_name: ${{ github.ref_name }}-artifacts.zip
          asset_content_type: application/zip