name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # This triggers the workflow on version tags, like v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, macos-13]
        architecture: [x86_64, arm64]
        exclude:
          - os: windows-latest
            architecture: arm64
          - os: macos-latest
            architecture: x86_64
          - os: macos-13
            architecture: arm64
          

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build application with PyInstaller (NOT macOS x86_64)
        if: ${{ matrix.os != 'macos-13' || matrix.architecture != 'x86_64' }}
        run: |
          pyinstaller easydiver.spec --noconfirm
      
      - name: Build application with PyInstaller (macOS x86_64)
        if: ${{ matrix.os == 'macos-13' && matrix.architecture == 'x86_64' }}
        run: |
          pyinstaller easydiver-${{ matrix.os }}-${{ matrix.architecture }}.spec --noconfirm

      - name: Zip the output (Linux and macOS)
        if: runner.os != 'Windows'
        run: |
          zip -r EasyDiver-${{ matrix.os }}-${{ matrix.architecture }}.zip dist/EasyDiver

      - name: Zip the output (Windows)
        if: runner.os == 'Windows'
        run: |
          Compress-Archive -Path dist/EasyDiver -DestinationPath EasyDiver-${{ matrix.os }}-${{ matrix.architecture }}.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: easydiver-${{ matrix.os }}-${{ matrix.architecture }}
          path: EasyDiver-${{ matrix.os }}-${{ matrix.architecture }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts (Windows x86_64)
        uses: actions/download-artifact@v4
        with:
          name: easydiver-windows-latest-x86_64
          path: ./dist

      - name: Download build artifacts (macOS x86_64)
        uses: actions/download-artifact@v4
        with:
          name: easydiver-macos-13-x86_64
          path: ./dist

      - name: Download build artifacts (macOS arm64)
        uses: actions/download-artifact@v4
        with:
          name: easydiver-macos-latest-arm64
          path: ./dist

      - name: List directory contents
        run: ls -R ./dist

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.PAT }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            Release notes for ${{ github.ref }}.
          draft: false
          prerelease: false
          artifacts: ./dist/*.zip